"""Build a customer package without shipping the project's Python files."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_NAME = "DonghuaKoubo"


def _run(command: list[str], *, cwd: Path = ROOT) -> None:
    print("+", " ".join(command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def _platform(value: str) -> str:
    if value != "auto":
        return value
    return "windows" if sys.platform == "win32" else "macos" if sys.platform == "darwin" else "linux"


def _asset_pairs() -> list[tuple[Path, str]]:
    pairs: list[tuple[Path, str]] = []
    for relative in ("audio", "picturies", "data"):
        source = ROOT / relative
        if source.is_dir():
            pairs.append((source, relative))
    reference = ROOT / "src" / "copywriting_style_reference.md"
    if reference.is_file():
        pairs.append((reference, "src"))
    return pairs


def _write_spec(path: Path, name: str, target: str) -> None:
    datas = repr([(str(source), target) for source, target in _asset_pairs()])
    spec = f'''# Generated by tools/release/build_release.py
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

hiddenimports = [
    module for module in collect_submodules("src")
    if not module.startswith("src.tests")
] + collect_submodules("pyJianYingDraft")
datas = {datas} + collect_data_files("pyJianYingDraft")

block_cipher = None
a = Analysis(
    [r"{(ROOT / "src" / "__main__.py").as_posix()}"],
    pathex=[r"{ROOT.as_posix()}", r"{(ROOT / "vendor" / "pyJianYingDraft").as_posix()}"],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=["src.tests"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="{name}",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
)
coll = COLLECT(exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=False, name="{name}")
{f'app = BUNDLE(coll, name="{name}.app", icon=None, bundle_identifier="com.donghua.koubo")' if target == "macos" else ""}
'''
    path.write_text(spec, encoding="utf-8")


def _write_customer_files(result: Path, name: str, target: str) -> None:
    launch_target = (
        f"双击 {name}.app"
        if target == "macos"
        else f"双击 {name}.exe"
        if target == "windows"
        else f"运行 {name}"
    )
    (result / "README_使用说明.txt").write_text(
        "客户版使用说明\n\n"
        f"1. 请向软件提供方获取本机专用的 .env 配置文件，并放在本目录。\n"
        f"2. {launch_target} 启动程序。\n"
        "3. 请保持整个文件夹完整，不要单独移动主程序。\n"
        "4. 客户电脑需要另行安装 ffmpeg 和 ffprobe。\n",
        encoding="utf-8",
    )


def build(args: argparse.Namespace) -> Path:
    target = _platform(args.platform)
    if target not in {"windows", "macos", "linux"}:
        raise SystemExit("当前机器只支持 auto、windows、macos 或 linux 作为构建目标")
    if target != _platform("auto"):
        print(f"当前系统是 {_platform('auto')}，不能直接交叉构建 {target}。请在目标系统上运行。")
        raise SystemExit(2)
    try:
        import PyInstaller  # noqa: F401
    except ImportError as exc:
        raise SystemExit("缺少 PyInstaller，请先运行：python -m pip install pyinstaller") from exc

    output = (ROOT / args.output).resolve() if not Path(args.output).is_absolute() else Path(args.output)
    work = ROOT / "build" / "release"
    if args.clean:
        shutil.rmtree(work, ignore_errors=True)
        shutil.rmtree(output / args.name, ignore_errors=True)
        shutil.rmtree(output / f"{args.name}.app", ignore_errors=True)
    work.mkdir(parents=True, exist_ok=True)
    spec_path = work / f"{args.name}.spec"
    _write_spec(spec_path, args.name, target)

    _run([sys.executable, "-m", "py_compile", "src/__main__.py", "src/qt_app.py", "src/pipeline_runtime.py"])
    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        str(output),
        "--workpath",
        str(work / "pyinstaller"),
        str(spec_path),
    ]
    _run(command)
    if target == "macos":
        bundle = output / f"{args.name}.app"
        result = output / args.name
        shutil.rmtree(result, ignore_errors=True)
        result.mkdir(parents=True, exist_ok=True)
        shutil.move(str(bundle), str(result / bundle.name))
    else:
        result = output / args.name
    _write_customer_files(result, args.name, target)
    if not args.keep_work:
        shutil.rmtree(work, ignore_errors=True)
        try:
            (ROOT / "build").rmdir()
        except OSError:
            pass
    print(f"发版完成：{result}")
    if args.keep_work:
        print(f"已保留构建中间文件：{work}")
    else:
        print("构建中间文件已自动清理")
    print("客户包不包含 .py 源文件；配置文件请由软件提供方单独发放。")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--platform", choices=("auto", "windows", "macos", "linux"), default="auto")
    parser.add_argument("--name", default=DEFAULT_NAME)
    parser.add_argument("--output", default="release")
    parser.add_argument("--clean", action="store_true", help="清理上一次构建目录")
    parser.add_argument(
        "--keep-work",
        action="store_true",
        help="保留 PyInstaller 中间文件，便于构建失败时排查",
    )
    args = parser.parse_args()
    build(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
